"""empty message

Revision ID: 07977348e74a
Revises: b3a4c9e8575d
Create Date: 2019-12-05 22:45:16.725147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07977348e74a'
down_revision = 'b3a4c9e8575d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('code_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('expertise',
    sa.Column('expertise_number', sa.String(), nullable=False),
    sa.Column('expertise_conclusion', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('expert_FIO', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('expertise_number')
    )
    op.create_table('technical_document',
    sa.Column('passport_code', sa.BigInteger(), nullable=False),
    sa.Column('manual', sa.String(), nullable=True),
    sa.Column('specific', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('passport_code')
    )
    op.create_table('enter_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enter_conclusion_number', sa.Integer(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('expertise_number', sa.String(), nullable=True),
    sa.Column('passport', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['classification.code'], ),
    sa.ForeignKeyConstraint(['expertise_number'], ['expertise.expertise_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplementary_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('technical_doc', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['technical_doc'], ['technical_document.passport_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplementary_document')
    op.drop_table('enter_statement')
    op.drop_table('technical_document')
    op.drop_table('expertise')
    op.drop_table('classification')
    # ### end Alembic commands ###
