"""empty message

Revision ID: 28502fbdf676
Revises: 897010978584
Create Date: 2019-12-04 19:05:05.011130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28502fbdf676'
down_revision = '897010978584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification',
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('code_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enter_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enter_conclusion_number', sa.Integer(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('passport', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['classification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enter_statement')
    op.drop_table('classification')
    # ### end Alembic commands ###
