"""empty message

Revision ID: 897010978584
Revises: 
Create Date: 2019-12-04 14:43:43.777495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897010978584'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.Integer(), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIO_director', sa.String(length=64), nullable=True),
    sa.Column('FIO_executor', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('mail_address', sa.String(length=64), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addition_number', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(length=128), nullable=True),
    sa.Column('contract', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appendix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appendix_number', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(length=128), nullable=True),
    sa.Column('contract', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conclusion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conclusion_number', sa.Integer(), nullable=True),
    sa.Column('executor_info', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(length=128), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['executor_info'], ['executor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legalentity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('legalentity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['legalentity_id'], ['legalentity.id'], )
    )
    op.create_table('statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_number', sa.Integer(), nullable=True),
    sa.Column('INN', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['INN'], ['legalentity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statement')
    op.drop_table('contracts')
    op.drop_table('legalentity')
    op.drop_table('conclusion')
    op.drop_table('appendix')
    op.drop_table('addition')
    op.drop_table('license')
    op.drop_table('executor')
    op.drop_table('contract')
    op.drop_table('client_user')
    # ### end Alembic commands ###
