"""empty message

Revision ID: b15ff883236d
Revises: 245c53cdff70
Create Date: 2019-12-16 21:34:43.661821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15ff883236d'
down_revision = '245c53cdff70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legalentity', sa.Column('real_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legalentity', 'real_address')
    # ### end Alembic commands ###
